version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOG_DIR=/usr/src/app/logs
    volumes:
      - logs:/usr/src/app/logs
      - uploads:/usr/src/app/uploads
    ports:
      - '8084:8084'

volumes:
  logs:
  uploads:
